"""Add user

Revision ID: 014a324638f2
Revises: 8a55722068d1
Create Date: 2024-11-29 22:26:03.455217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014a324638f2'
down_revision = '8a55722068d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
